services:
  - type: cron
    name: monitor-planilha-xlsx
    runtime: python
    repo: https://github.com/CaioAnjos30/monitor-render
    branch: main
    schedule: */2 * * * *  # A cada 2 minutos
    buildCommand: ""
    startCommand: python monitor_planilha.py
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: cron
    name: gatilho-automacao
    runtime: python
    repo: https://github.com/CaioAnjos30/monitor-render
    branch: main
    schedule: */2 * * * *  # A cada 2 minutos
    buildCommand: ""
    startCommand: python gatilho_automacao.py
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
